[project]
name = "langgraph-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.27",
    "langgraph>=0.2.0",
    "langsmith>=0.4.31",
    "ruff>=0.13.2",
]
